Algoritmo "ANTECESSOR"
// Disciplina  : [Linguagem e Lógica de Programação com Visualg]
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicita dois números para o usuário, soma e exibe o resultado.
// Autor(a)    : Saira da S. Pereira
// Data atual  : 26/03/2026

Var
// Seção de Declarações das variáveis
numero:inteiro
resultado:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreva ("Digite um número: ")
Leia (numero)
resultado<- numero - 1
Escreva ("O antecessor do número digitado é:",resultado)

FimAlgoritmo