Algoritmo "area_quadrado"
// Disciplina  : Lógica de Programação VisualG
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicita o valor do lado, calcula a área do quadrado
// Autor(a)    : Saira Silva
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis
   lado: inteiro
   area: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite o valor do lado do quadrado: ")
   leia(lado)

   area <- lado * lado

   escreva("A área do quadrado é igual a:", area, "cm²")

Fimalgoritmo