Algoritmo "AREA DO CIRCULO"
// Disciplina  : [Lógica de Programação com VisualG]
// Professor   : Jailson Costa dos Santos
// Descrição   : calcula a area de um círculo
// Autor(a)    : Saira da Silva Pereira
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis
raio: real
resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
 Escreva("Digite o valor do raio para calcular a area do círculo: ")
 leia (raio)
 resultado<- pi * raio^2
 Escreva("O valor da area do circulo calculado é: ",resultado)

Fimalgoritmo