Algoritmo "AREA DE UM RETANGULO"
// Disciplina  : [Linguagem e Lógica de Programação VisualG]
// Professor   : Jailson Costa dos Santos
// Descrição   : calcula a area de um retângulo
// Autor(a)    : Saira da Silva Pereira
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis 
base: inteiro
altura: inteiro
resultado: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreva("Digite o valor da base: ")
 leia(base)
 Escreva("Digite o valor da altura: ")
 leia(altura)
 resultado<-base*altura
 Escreva("O valor da area do retângulo é: ",resultado)
 
Fimalgoritmo