Algoritmo "AREA DE UM TRIANGULO"
// Disciplina  : [Lógica de Programação com VisualG]
// Professor   : Jailson Costa dos Santos
// Descrição   : calcula a area de um triângulo
// Autor(a)    : Saira da Silva Pereira
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis
base: inteiro
altura: inteiro
resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
 Escreva("Digite o valor da base: ")
 leia(base)
 Escreva("Digite o valor da altura: ")
 leia(altura)
 resultado<-base*altura/2
 Escreva("O valor da area do triângulo é: ",resultado)

Fimalgoritmo