Algoritmo "celsius_fahrenheit"
// Disciplina  : [Lógica de Programação com visualG]
// Professor   : Jailson Costa do Santos
// Descrição   : Ler uma temperatura em graus Celsius e apresentá-la convertida em graus Fahrenheit.
// Autor(a)    : Saira da Silva Pereira
// Data atual  : 18/04/2026

Var
// Seção de Declarações das variáveis 
   Celsius, Fahrenheit: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Digite a temperatura em Celsius: ")
   Leia(Celsius)
   Fahrenheit <- (9 * Celsius + 160) / 5
   Escreva("A temperatura em Fahrenheit é de: ",Fahrenheit)

Fimalgoritmo