Algoritmo "Cronometro"

// Disciplina  : [Lógica de Programação com Visualg]
// Professor   : Jailson Costa dos Santos
// Descrição   : Cronometro
// Autor(a)    : Saira
// Data atual  : 14/04/2026

Var

// Seção de Declarações das variáveis
   minutos,segundos:inteiro

Inicio

// Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Exemplo de Cronometro")
   para minutos de 0 até 59 passo 1 faça
      para segundos de 0 até 59 passo 1 faça
         Escreval(minutos, " : ", segundos)
         tempo 200

      fimpara
   fimpara

Fimalgoritmo
