Algoritmo "Divisao com 2 divisores"
// Disciplina  : [Lógica de Programação com VisualG]
// Professor   : Jailson Costa dos Santos
// Descrição   : Dividir um número com dois divisores
// Autor(a)    : Saira da S. Pereira
// Data atual  : 01/04/2026
Var
Numero: real
Resultado: real

Inicio
Escreva ("Digite um número para a divisão: ")
Leia (Numero)
Resultado<-Numero / 2
Escreva ("O resultado da divisão por 2 é:", Resultado)

Fimalgoritmo