Algoritmo "Divisao"
// Disciplina  : [Linguagem e Lógica de Programação com Visualg]
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicita dois números para o usuário, soma e exibe o resultado.
// Autor(a)    : Saira da S. Pereira
// Data atual  : 26/03/2026

Var
// Seção de Declarações das variáveis
numero01:inteiro
numero02:inteiro
resultado:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreva ("Digite o primeiro número: ")
Leia (numero01)
Escreva ("Digite o segundo número: ")
Leia (numero02)
Resultado<-numero01/numero02
Escreva ("A divisão dos números digitados é:",Resultado)

FimAlgoritmo