Algoritmo "dobro_area_do_quadrado"
// Disciplina  : Lógica de Programação com VisualG
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicita um número, calcula a área do quadrado e mostra o  dobro
// Autor(a)    : Saira Silva
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis
   lado: inteiro
   area: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite um valor para o lado do quadrado: ")
   leia(lado)

   area <- (lado * lado) * 2

   escreva("O dobro da área do quadrado é igual a:", area, "cm²")



Fimalgoritmo