Algoritmo "EstruturaDeRepeticao"
// Disciplina  : [Lógica de Programação com VisualG]
// Professor   : Jailson Costa dos Santos
// Descrição   : Exemplo de estrutura de repetição
// Autor(a)    : Saira
// Data atual  : 01/04/2026

Var
// Seção de Declarações das variáveis
contadora: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
enquanto contadora<5 faça
escreval("Hello")
contadora<-contadora+1

Fimenquanto
Fimalgoritmo