Algoritmo "Numeros_Inteiros_Impares"

// Disciplina : (Lógica de Programação com VisualG)
// Professor  : Jailson Costa dos Santos
// Descrição  : Mostrar os números inteiros impares até 20.
// Autor(a)   : Saira da Silva Pereira
// Data atual : 05/04/2026

Var
   // Seção de Declarações das variáveis
   contadora: inteiro

Inicio

   // Seção de Comandos, procedimento, funções, operadores, etc...
   enquanto contadora < 21 faca
      se contadora mod 2 = 1 entao
         Escreval (contadora)
      fimse
      contadora <- contadora + 1

   fimenquanto

Fimalgoritmo