Algoritmo "Par ou Impar"
// Disciplina  : [Lógica de Programação com VisualG]
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicitar um valor e exibir se o número é par ou impar
// Autor(a)    : Saira da S. Pereira
// Data atual  : 01/04/2026
Var
Numero: real

Inicio
Escreva ("Digite um número para a operação: ")
Leia (Numero)
Se Numero mod 2 = 0 então
Escreval ("O número é Par!")
Senao
Escreva ("O número é Impar!")

FimSe

Fimalgoritmo